name: pos_azmi
description: "Aplikasi POS untuk penjualan."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  pusher_channels_flutter: ^2.2.1
  blue_thermal_printer: ^1.1.5 
  provider: ^6.1.5
  shared_preferences: ^2.2.3
  logger: ^2.5.0
  intl: ^0.19.0
  rename: ^3.1.0
  audioplayers: ^5.2.1
  flutter_dotenv: ^5.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^11.1.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/images/logo.png
    - assets/audio/terima-order.wav

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
